options = [
    {'uz': 'Bilyard', 'ru': 'Бильярд', 'en': 'Billiards'},
    {'uz': 'Stol tennisi', 'ru': 'Настольный теннис', 'en': 'Table Tennis'},
    {'uz': 'Tennis', 'ru': 'Теннис', 'en': 'Tennis'},
    {'uz': 'Bovling', 'ru': 'Боулинг', 'en': 'Bowling'},
    {'uz': 'Mini stadion', 'ru': 'Мини-стадион', 'en': 'Mini Stadium'},
    {'uz': 'Golf', 'ru': 'Гольф', 'en': 'Golf'},
    {'uz': 'Terassa', 'ru': 'Терраса', 'en': 'Terrace'},
    {'uz': 'Karaoke', 'ru': 'Караоке', 'en': 'Karaoke'},
    {'uz': 'Tapchan', 'ru': 'Тапчан', 'en': 'Tapchan'},
    {'uz': 'Sauna (finiskiy)', 'ru': 'Сауна (финская)', 'en': 'Sauna (Finnish)'},
    {'uz': 'Sauna (turketiskiy)', 'ru': 'Сауна (турецкая)', 'en': 'Sauna (Turkish)'},
    {'uz': 'Televizor', 'ru': 'Телевизор', 'en': 'Television'},
    {'uz': 'Konditsioner', 'ru': 'Кондиционер', 'en': 'Air Conditioner'},
    {'uz': 'Sanuzel', 'ru': 'Санузел', 'en': 'Restroom'},
    {'uz': 'Wi-Fi', 'ru': 'Wi-Fi', 'en': 'Wi-Fi'},
    {'uz': 'Mangal', 'ru': 'Мангал', 'en': 'Barbecue Grill'},
    {'uz': 'Barbekyu', 'ru': 'Барбекю', 'en': 'Barbecue'},
    {'uz': 'Kompyuter', 'ru': 'Компьютер', 'en': 'Computer'},
    {'uz': 'Chiroyli joy', 'ru': 'Красивое место', 'en': 'Beautiful Place'},
    {'uz': 'Kinoteatr', 'ru': 'Кинотеатр', 'en': 'Cinema'},
    {'uz': 'Tuzli xona', 'ru': 'Соляная комната', 'en': 'Salt Room'},
    {'uz': 'PlayStation 3', 'ru': 'PlayStation 3', 'en': 'PlayStation 3'},
    {'uz': 'PlayStation 4', 'ru': 'PlayStation 4', 'en': 'PlayStation 4'},
    {'uz': 'PlayStation 5', 'ru': 'PlayStation 5', 'en': 'PlayStation 5'},
    {'uz': 'Qishki basseyn', 'ru': 'Зимний бассейн', 'en': 'Winter Pool'},
    {'uz': 'Yozgi basseyn', 'ru': 'Летний бассейн', 'en': 'Summer Pool'},
    {'uz': 'Yozgi oshxona', 'ru': 'Летняя кухня', 'en': 'Summer Kitchen'},
    {'uz': 'Qishki oshxona', 'ru': 'Зимняя кухня', 'en': 'Winter Kitchen'},
    {'uz': 'Bolalar maydonchasi', 'ru': 'Детская площадка', 'en': 'Children\'s Playground'},
    {'uz': 'Basketbol stadioni', 'ru': 'Баскетбольный стадион', 'en': 'Basketball Stadium'},
    {'uz': 'Volebol stadioni', 'ru': 'Волейбольный стадион', 'en': 'Volleyball Stadium'},
    {'uz': 'Stol futboli', 'ru': 'Настольный футбол', 'en': 'Table Football'},
    {'uz': 'Namoz xona', 'ru': 'Молитвенная комната', 'en': 'Prayer Room'},
    {'uz': 'Qishki bog\'', 'ru': 'Зимний сад', 'en': 'Winter Garden'},
    {'uz': 'Balkon', 'ru': 'Балкон', 'en': 'Balcony'},
    {'uz': 'Favvora', 'ru': 'Фонтан', 'en': 'Fountain'},
    {'uz': 'Sharshara', 'ru': 'Водопад', 'en': 'Waterfall'}
]
